CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'amsaq_user'@'%' IDENTIFIED BY 'DB_PASSWORD_PLACEHOLDER';
GRANT ALL PRIVILEGES ON wordpress.* TO 'amsaq_user'@'%';
FLUSH PRIVILEGES;
